-- Run in SQL Editor as postgres. Synthetic accounts/data never commit.
begin;
do $$ declare u uuid; t uuid; s uuid; p uuid; ids jsonb := '{}'::jsonb; kind text; begin
  foreach kind in array array['owner','member','editor','outsider'] loop
    u := gen_random_uuid();
    insert into auth.users(id,email,raw_user_meta_data) values(u,u::text||'@psalmo-test.invalid','{"display_name":"Policy fixture"}');
    ids := ids || jsonb_build_object(kind,u);
  end loop;
  insert into public.teams(name,created_by,admin_managed) values('Rollback policy fixture',(ids->>'owner')::uuid,true) returning id into t;
  ids := ids || jsonb_build_object('team',t);
  insert into public.team_memberships(team_id,user_id) values(t,(ids->>'member')::uuid),(t,(ids->>'editor')::uuid);
  foreach kind in array array['member','editor'] loop
    insert into public.roster_people(team_id,name,account_id) values(t,kind,(ids->>kind)::uuid) returning id into p;
    ids := ids || jsonb_build_object(kind||'_person',p);
  end loop;
  insert into public.roster_people(team_id,name) values(t,'Before signup') returning id into p;
  ids := ids || jsonb_build_object('unlinked',p);
  foreach kind in array array['ir_1_2','ir_3'] loop
    insert into public.services(team_id,title,service_type,service_date,created_by)
      values(t,kind,kind::public.service_type,'2026-09-20T00:00:00+07',(ids->>'owner')::uuid) returning id into s;
    ids := ids || jsonb_build_object(kind,s);
  end loop;
  insert into public.weekly_schedules(team_id,sunday) values(t,'2026-09-20');
  insert into public.invites(team_id,token_hash,expires_at,created_by) values(t,encode(digest('blocked-'||t::text,'sha256'),'hex'),now()+interval '1 day',(ids->>'owner')::uuid);
  insert into public.teams(name,created_by) values('Rollback prototype fixture',(ids->>'owner')::uuid) returning id into t;
  ids := ids || jsonb_build_object('prototype',t);
  insert into public.roster_people(team_id,name) values(t,'Foreign church name') returning id into p;
  ids := ids || jsonb_build_object('foreign_person',p);
  insert into public.songs(team_id,title,created_by) values(t,'Foreign church song',(ids->>'owner')::uuid) returning id into p;
  ids := ids || jsonb_build_object('foreign_song',p);
  perform set_config('psalmo.fixture',ids::text,true);
end $$;
set local role authenticated;
do $$ declare ids jsonb := current_setting('psalmo.fixture')::jsonb; t uuid := (ids->>'team')::uuid; s uuid := (ids->>'ir_1_2')::uuid;
  song uuid; item uuid; revision_before integer; revision_after integer; projection jsonb; rows_changed integer; prototype_token text;
begin
  perform set_config('request.jwt.claim.sub',ids->>'outsider',true);
  begin perform public.set_team_member_role(t,(ids->>'member')::uuid,'admin'); raise exception 'FAIL outsider promotion'; exception when raise_exception then if sqlerrm='FAIL outsider promotion' then raise; end if; end;
  begin perform public.remove_team_member(t,(ids->>'member')::uuid); raise exception 'FAIL outsider kick'; exception when raise_exception then if sqlerrm='FAIL outsider kick' then raise; end if; end;
  begin perform public.link_roster_account((ids->>'unlinked')::uuid,ids->>'outsider'||'@psalmo-test.invalid'); raise exception 'FAIL outsider link'; exception when raise_exception then if sqlerrm='FAIL outsider link' then raise; end if; end;
  begin perform public.read_weekly_schedule(t,'2026-09-20','2026-09-20'); raise exception 'FAIL cross church schedule'; exception when raise_exception then if sqlerrm='FAIL cross church schedule' then raise; end if; end;
  assert not exists(select 1 from public.services where id=s), 'outsider services';
  perform set_config('request.jwt.claim.sub',ids->>'owner',true);
  begin perform public.link_roster_account((ids->>'unlinked')::uuid,'not-registered@psalmo-test.invalid'); raise exception 'FAIL missing account accepted'; exception when raise_exception then if sqlerrm='FAIL missing account accepted' then raise; end if; end;
  perform public.link_roster_account((ids->>'unlinked')::uuid,upper(ids->>'outsider'||'@psalmo-test.invalid'));
  assert exists(select 1 from public.team_memberships where team_id=t and user_id=(ids->>'outsider')::uuid), 'link grants membership';
  assert exists(select 1 from public.roster_people where id=(ids->>'unlinked')::uuid and account_id=(ids->>'outsider')::uuid), 'link account';
  begin perform public.create_team_invite(t); raise exception 'FAIL new church invite'; exception when raise_exception then if sqlerrm='FAIL new church invite' then raise; end if; end;
  begin perform public.accept_team_invite('blocked-'||t::text); raise exception 'FAIL new church accept'; exception when raise_exception then if sqlerrm='FAIL new church accept' then raise; end if; end;
  begin insert into public.service_assignments(service_id,person_id,role_name) values(s,(ids->>'foreign_person')::uuid,'Drum'); raise exception 'FAIL foreign person'; exception when raise_exception then if sqlerrm='FAIL foreign person' then raise; end if; end;
  insert into public.service_assignments(service_id,person_id,role_name,position) values(s,(ids->>'member_person')::uuid,'Singer',0),(s,(ids->>'editor_person')::uuid,'WL',1);
  insert into public.service_assignments(service_id,person_id,role_name,position) values(s,(ids->>'member_person')::uuid,'MD',2),(s,(ids->>'editor_person')::uuid,'Singer',3);
  insert into public.service_assignments(service_id,user_id,role_name,display_name,position) values(s,(ids->>'outsider')::uuid,'Guest','Typed guest/group',4);
  assert not exists(select 1 from public.service_assignments where service_id=s and user_id is not null), 'new church ignores legacy user link';
  insert into public.service_notes(service_id,body,created_by) values(s,'Secret preparation note',(ids->>'owner')::uuid);
  insert into public.media_references(service_id,label,url) values(s,'Private rehearsal','https://example.com/private');
  perform public.set_song_editor(t,(ids->>'editor')::uuid,true);
  song := public.save_library_song(t,null,'{"title":"Snapshot song","key":"C","bpm":100,"time_signature":"4/4","lyrics":"[Verse]\nOriginal"}', '[{"label":"Original video","url":"https://youtu.be/dQw4w9WgXcQ"},{"label":"Alternate","url":"https://youtube.com/watch?v=dQw4w9WgXcQ"}]');
  perform public.append_service_songs(s,canonical_song_id=>song);
  begin insert into public.setlist_items(setlist_id,song_id,position) select id,(ids->>'foreign_song')::uuid,20 from public.setlists where service_id=s; raise exception 'FAIL direct foreign song linkage'; exception when raise_exception then if sqlerrm='FAIL direct foreign song linkage' then raise; end if; end;
  perform public.append_service_songs(s,array['Manual song','Third song']);
  assert not exists(select 1 from public.setlists where service_id=(ids->>'ir_3')::uuid), 'IR3 independent from shared IR1/2';
  begin perform public.append_service_songs(s,canonical_song_id=>(ids->>'foreign_song')::uuid); raise exception 'FAIL foreign song'; exception when raise_exception then if sqlerrm='FAIL foreign song' then raise; end if; end;
  perform public.save_library_song(t,song,'{"title":"Changed library title","key":"D","bpm":120,"lyrics":"Changed lyrics"}','[]');
  assert exists(select 1 from public.setlist_items i join public.setlists l on l.id=i.setlist_id where l.service_id=s and i.proposed_title='Snapshot song' and i.key='C' and i.bpm=100 and i.lyrics_or_chords like '%Original%' and i.arrangement_url like '%dQw4w9WgXcQ'), 'library snapshot isolation';
  assert exists(select 1 from public.setlist_items i join public.setlists l on l.id=i.setlist_id where l.service_id=s and jsonb_array_length(i.library_references)=2 and i.library_references->1->>'label'='Alternate'), 'ordered reference snapshot isolation';
  perform set_config('request.jwt.claim.sub',ids->>'member',true);
  assert not exists(select 1 from public.services where id=s), 'ordinary member cannot see draft';
  assert not public.service_edit_permission(s), 'actual MD without permanent editor cannot edit';
  assert not exists(select 1 from public.read_weekly_schedule(t,'2026-09-20','2026-09-20')), 'unpublished projection hidden';
  perform set_config('request.jwt.claim.sub',ids->>'editor',true);
  assert public.service_edit_permission(s), 'permanent editor actual WL draft';
  assert not public.service_edit_permission((ids->>'ir_3')::uuid), 'editor no IR3 duty';
  assert exists(select 1 from public.services where id=s), 'editor draft visible';
  perform public.append_service_songs(s,array['Editor song']);
  begin perform public.append_service_songs((ids->>'ir_3')::uuid,array['Illegal song']); raise exception 'FAIL unrelated edit'; exception when raise_exception then if sqlerrm='FAIL unrelated edit' then raise; end if; end;
  update public.services set status='approved' where id=s; get diagnostics rows_changed=row_count; assert rows_changed=0, 'WL cannot approve';
  update public.service_notes set body='Illegal' where service_id=s; get diagnostics rows_changed=row_count; assert rows_changed=0, 'WL cannot edit shared notes';
  select i.id,l.revision into item,revision_before from public.setlist_items i join public.setlists l on l.id=i.setlist_id where l.service_id=s order by i.position limit 1;
  update public.setlist_items set bpm=137,time_signature='6/8',notes='Latihan setting' where id=item;
  get diagnostics rows_changed=row_count; assert rows_changed=1, 'assigned WL editor can save click settings';
  assert exists(select 1 from public.setlist_items where id=item and bpm=137 and time_signature='6/8' and notes='Latihan setting' and key='C' and lyrics_or_chords like '%Original%' and jsonb_array_length(library_references)=2), 'click edit preserves arrangement columns';
  assert exists(select 1 from public.songs where id=song and default_bpm=120), 'click edit leaves canonical library unchanged';
  select revision into revision_before from public.setlists where service_id=s;
  revision_after := public.move_setlist_item(item,'down',revision_before);
  assert revision_after>revision_before, 'revision advanced';
  begin perform public.move_setlist_item(item,'up',revision_before); raise exception 'FAIL stale revision accepted'; exception when sqlstate 'PT409' then null; end;
  perform set_config('request.jwt.claim.sub',ids->>'owner',true);
  update public.weekly_schedules set published_at=now() where team_id=t;
  perform set_config('request.jwt.claim.sub',ids->>'outsider',true); -- now linked but unassigned
  select value into projection from public.read_weekly_schedule(t,'2026-09-20','2026-09-20') value;
  assert projection->'services'->0->'roster' is not null, 'published roster readable';
  assert projection::text not like '%Secret preparation%' and projection::text not like '%Private rehearsal%' and projection::text not like '%lyrics%' and projection::text not like '%account_id%', 'projection no content/account leak';
  assert not exists(select 1 from public.services where id=s), 'unassigned draft blocked';
  perform set_config('request.jwt.claim.sub',ids->>'owner',true); update public.services set status='approved' where id=s;
  perform set_config('request.jwt.claim.sub',ids->>'outsider',true);
  assert not exists(select 1 from public.services where id=s), 'unassigned approved blocked';
  assert not exists(select 1 from public.setlists where service_id=s), 'unassigned setlist blocked';
  assert not exists(select 1 from public.service_notes where service_id=s), 'unassigned notes blocked';
  assert not exists(select 1 from public.media_references where service_id=s), 'unassigned media blocked';
  assert not exists(select 1 from public.service_assignments where service_id=s), 'direct roster must use projection';
  perform set_config('request.jwt.claim.sub',ids->>'member',true);
  assert exists(select 1 from public.services where id=s), 'assigned approved visible';
  assert not public.service_edit_permission(s), 'ordinary duty not editor';
  update public.setlist_items set bpm=200,notes='Illegal ordinary click change' where id=item;
  get diagnostics rows_changed=row_count; assert rows_changed=0, 'ordinary assigned member cannot save click settings';
  perform set_config('request.jwt.claim.sub',ids->>'owner',true);
  delete from public.service_assignments where service_id=s and person_id=(ids->>'editor_person')::uuid;
  perform set_config('request.jwt.claim.sub',ids->>'editor',true);
  assert not exists(select 1 from public.services where id=s), 'off-duty editor service hidden';
  update public.setlist_items set bpm=200 where id=item;
  get diagnostics rows_changed=row_count; assert rows_changed=0, 'off-duty editor cannot save click settings';
  perform public.save_library_song(t,song,'{"title":"Off duty editor update","lyrics":"Library still editable"}','[]');
  perform set_config('request.jwt.claim.sub',ids->>'owner',true);
  perform public.kick_roster_person((ids->>'member_person')::uuid);
  assert exists(select 1 from public.service_assignments where service_id=s and display_name='member'), 'historical name retained';
  perform set_config('request.jwt.claim.sub',ids->>'member',true);
  assert not exists(select 1 from public.services where id=s), 'kicked assignment cannot bypass membership';
  update public.setlist_items set bpm=200 where id=item;
  get diagnostics rows_changed=row_count; assert rows_changed=0, 'kicked member cannot save click settings';
  assert not exists(select 1 from public.songs where id=song), 'kicked library blocked';
  begin perform public.read_weekly_schedule(t,'2026-09-20','2026-09-20'); raise exception 'FAIL kicked schedule'; exception when raise_exception then if sqlerrm='FAIL kicked schedule' then raise; end if; end;
  -- The old prototype invite records/path remain usable, with member checks.
  perform set_config('request.jwt.claim.sub',ids->>'owner',true);
  select token into prototype_token from public.create_team_invite((ids->>'prototype')::uuid);
  perform set_config('request.jwt.claim.sub',ids->>'member',true);
  perform public.accept_team_invite(prototype_token);
  assert exists(select 1 from public.team_memberships where team_id=(ids->>'prototype')::uuid and user_id=(ids->>'member')::uuid), 'prototype invite preserved';
end $$;
reset role;
select 'PASS: linking, duty RLS, publication, snapshot, click-settings isolation/permissions, revision conflict, membership guards, kick history; all fixtures rolled back' as result;
rollback;
